### ISSUE TITLE
Fix average ratings not updating on reivew submit due to the delay of the trigger running

### ISSUE THREAD

**Issue by sheehan-j** [Code-Goblins2024/swamp-review#39]

**Comment by erobx** [comment]
Added a Supabase function that returns the category id, name and average rating for each category for a specific housing id. Created a Supabase RPC query in the housingQueries.js file to be called on the HousingPage.jsx component. We are still returning data from the average_ratings table for compatibility.

The changes are currently in the supabase-functions branch.
